trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UseDotNet@2
  inputs:
     packageType: 'sdk'
     version: '6.x'
- task: DotNetCoreCLI@2
  displayName: tests
  inputs:
    command: test
    projects: '**/*Payslip*[Tt]ests/*.csproj'
    publishTestResults: true
    arguments: '--configuration $(buildConfiguration)'