name: payslip-api
version: "3.7"
  
services:
  payslip-api:
    image: vitornikiforck/payslip:latest
    build:
      context: ./
      dockerfile: ./src/Payslip.Api/Dockerfile
    ports:
      - 80:80
      - 443:443
