version: "3.7"

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    container_name: sql-server-payslip
    restart: always 
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
      
  payslip-api:
    image: vitornikiforck/payslip:latest
    container_name: payslip-api
    restart: always
    environment:
      - ASPNETCORE_URLS=http://+
      - ASPNETCORE_ENVIRONMENT=Development
      - AppSettings__ConnectionString=Data Source=host.docker.internal; Initial Catalog=PayslipDbContext; User=sa; Password=P@ssw0rd; MultipleActiveResultSets=true
    ports:
      - 9000:80