version: "3.7"

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    container_name: sql-server-payslip
    restart: always 
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
      
  payslip-api:
    image: vitornikiforck/payslip:latest
    container_name: payslip-api
    environment:
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=9001
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/var/https/aspnetapp.pfx
      - AppSettings__ConnectionString=Data Source=host.docker.internal; Initial Catalog=PayslipDbContext; User=sa; Password=P@ssw0rd; MultipleActiveResultSets=true
    ports:
      - 9000:80
      - 9001:443
    volumes:
      - ./configs:/var/https